name: dependency-review

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  review:
    name: dependency review
    if: ${{ github.event.repository.private == false }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Dependency Review
        uses: actions/dependency-review-action@v5.0.0
        with:
          fail-on-severity: moderate
